### ISSUE TITLE
RRmanger open error

### ISSUE THREAD

**Issue by zhangyongen** [T-REX-XP/RRManager#83]
RR manager open error:
2.0.79：Error during RRM initialization: TypeError: Cannot read properties of null (reading'rr_manager config')
updated to 2.0.81：Error during RRM initialization: TypeError: self.getConf is not a function

my synology nas run at 7.2.2 update2

**Comment by kurobirds** [comment]
I fixed it. Please follow these steps:
1. Uninstall RR Manager (Remove all data).
2. Uninstall Python 3.11 (Remove all data).
3. Reinstall Python 3.11.
4. Install RR Manager v2.0.79.

**Comment by sbridge88** [comment]
The problem will not be solved even if you do the same thing.

**Comment by sebaguse** [comment]
I have exacly same problem, tried above solution from @kurobirds but it didn't resolve the problem for me, any ideas how to fix it?

**Comment by kurobirds** [comment]
Try this:
1. Log in to your NAS via a browser.
2. Open the browser console (F12).
3. Copy and paste the following code into the console:
```js
const rrConfig = await SYNOCOMMUNITY.RRManager.SynoApiProvider.callCustomScript("getConfig.cgi");
localStorage.setItem("rrConfig", JSON.stringify(rrConfig));
```
4. Press Enter.
5. Open RR Manager again.

**Comment by sbridge88** [comment]
Error message....not working...

 Uncaught ReferenceError: SYNOCOMMUNITY is not defined  at <anonymous>:1:18

**Comment by SatellaPoi** [comment]
Maybe can try my modified version as a temporary workaround until the author fixes the bug.[release](https://github.com/SatellaPoi/RRManager/releases/tag/v2.0.80-fixed2)

**Comment by gravitation-ch** [comment]
> Error message....not working...
> 
> Uncaught ReferenceError: SYNOCOMMUNITY is not defined at :1:18

same to you

**Comment by kurobirds** [comment]
> > Error message....not working...
> > 
> > Uncaught ReferenceError: SYNOCOMMUNITY is not defined at :1:18
> 
> same to you

Is RR Manager installed before you tried running the script?

**Comment by gravitation-ch** [comment]
> > > Error message....not working...
> > > Uncaught ReferenceError: SYNOCOMMUNITY is not defined at :1:18
> > 
> > 
> > same to you
> 
> Is RR Manager installed before you tried running the script?

in stalled already v2.0.80

**Comment by kurobirds** [comment]
> > > > Error message....not working...
> > > > Uncaught ReferenceError: SYNOCOMMUNITY is not defined at :1:18
> > > 
> > > 
> > > same to you
> > 
> > Is RR Manager installed before you tried running the script?
> 
> in stalled already v2.0.80

Please run the following command and retry:
```js
Ext.ns('SYNOCOMMUNITY.RRManager');
```
I’ll try to reproduce your issue.

**Comment by gravitation-ch** [comment]
> I’ll try to reproduce your issue.

const rrConfig = await SYNOCOMMUNITY.RRManager.SynoApiProvider.callCustomScript("getConfig.cgi");
localStorage.setItem("rrConfig", JSON.stringify(rrConfig));
VM3415:1 Uncaught ReferenceError: SYNOCOMMUNITY is not defined
    at <anonymous>:1:18
(匿名) @ VM3415:1
Ext.ns('SYNOCOMMUNITY.RRManager');
{}
const rrConfig = await SYNOCOMMUNITY.RRManager.SynoApiProvider.callCustomScript("getConfig.cgi");
localStorage.setItem("rrConfig", JSON.stringify(rrConfig));
VM3425:1 Uncaught TypeError: Cannot read properties of undefined (reading 'callCustomScript')
    at <anonymous>:1:64

**Comment by kurobirds** [comment]
> > I’ll try to reproduce your issue.
> 
> const rrConfig = await SYNOCOMMUNITY.RRManager.SynoApiProvider.callCustomScript("getConfig.cgi");
> localStorage.setItem("rrConfig", JSON.stringify(rrConfig));
> VM3415:1 Uncaught ReferenceError: SYNOCOMMUNITY is not defined
>     at <anonymous>:1:18
> (匿名) @ VM3415:1
> Ext.ns('SYNOCOMMUNITY.RRManager');
> {}
> const rrConfig = await SYNOCOMMUNITY.RRManager.SynoApiProvider.callCustomScript("getConfig.cgi");
> localStorage.setItem("rrConfig", JSON.stringify(rrConfig));
> VM3425:1 Uncaught TypeError: Cannot read properties of undefined (reading 'callCustomScript')
>     at <anonymous>:1:64

I saw you resolved the issue on #82. Did it actually fix your issue?

**Comment by gravitation-ch** [comment]
> > > I’ll try to reproduce your issue.
> > 
> > 
> > const rrConfig = await SYNOCOMMUNITY.RRManager.SynoApiProvider.callCustomScript("getConfig.cgi");
> > localStorage.setItem("rrConfig", JSON.stringify(rrConfig));
> > VM3415:1 Uncaught ReferenceError: SYNOCOMMUNITY is not defined
> > at :1:18
> > (匿名) @ VM3415:1
> > Ext.ns('SYNOCOMMUNITY.RRManager');
> > {}
> > const rrConfig = await SYNOCOMMUNITY.RRManager.SynoApiProvider.callCustomScript("getConfig.cgi");
> > localStorage.setItem("rrConfig", JSON.stringify(rrConfig));
> > VM3425:1 Uncaught TypeError: Cannot read properties of undefined (reading 'callCustomScript')
> > at :1:64
> 
> I saw you resolved the issue on [#82](https://github.com/T-REX-XP/RRManager/issues/82). Did it actually fix your issue?

not be fixed, but when i installed v2.0.83 ,the error was changed.so closed #82.
now, error is "Cannot read properties of null (reading'rr_manager config')"

**Comment by gravitation-ch** [comment]
i closed #82 and then follow #83, 
so the output above-mentioned is just with v2.0.83

**Comment by kurobirds** [comment]
> i closed [#82](https://github.com/T-REX-XP/RRManager/issues/82) and then follow [#83](https://github.com/T-REX-XP/RRManager/issues/83), so the output above-mentioned is just with v2.0.83

Try this:

1. Uninstall RR Manager (Choose Erase all of the package data files).
2. Install RR Manager **v2.0.79**.
3. Open RR Manager—it will show an error, ignore it, but do not close RR Manager.
4. Open the browser console (F12).
5. Copy and paste the following code into the console:
```js
const rrConfig = await SYNOCOMMUNITY.RRManager.SynoApiProvider.callCustomScript("getConfig.cgi");
localStorage.setItem("rrConfig", JSON.stringify(rrConfig));
```
6. Press Enter.
7. Close and reopen RR Manager.

**Comment by king1011dzd** [comment]
> > 我关闭了 [#82](https://github.com/T-REX-XP/RRManager/issues/82)，然后按照 [#83](https://github.com/T-REX-XP/RRManager/issues/83)作，所以上面提到的输出只是 v2.0.83
> 
> 试试这个：
> 
> 1. 卸载 RR Manager（选择 Erase all of the package data files（擦除所有软件包数据文件））。
> 2. 安装 RR Manager **v2.0.79**。
> 3. 打开 RR Manager — 它将显示错误，忽略它，但不要关闭 RR Manager。
> 4. 打开浏览器控制台 （F12）。
> 5. 将以下代码复制并粘贴到控制台中：
> 
> const rrConfig = await SYNOCOMMUNITY.RRManager.SynoApiProvider.callCustomScript("getConfig.cgi");
> localStorage.setItem("rrConfig", JSON.stringify(rrConfig));
> 6. 按 Enter 键。
> 7. 关闭并重新打开 RR Manager。

2.0.79上使用，可以解决问题

**Comment by joutain** [comment]
可以考虑用RR作者改进的RR Manager版本
https://github.com/RROrg/RRManager

**Comment by bsy0318** [comment]
In the Control Panel, under 'Users & Groups' on the 'Users' tab, did you disable the 'admin' account?
If it was disabled, that seems to be the cause of this error.

**Comment by DeadPo01** [comment]
> > i closed [#82](https://github.com/T-REX-XP/RRManager/issues/82) and then follow [#83](https://github.com/T-REX-XP/RRManager/issues/83), so the output above-mentioned is just with v2.0.83
> 
> Try this:
> 
> 1. Uninstall RR Manager (Choose Erase all of the package data files).
> 2. Install RR Manager **v2.0.79**.
> 3. Open RR Manager—it will show an error, ignore it, but do not close RR Manager.
> 4. Open the browser console (F12).
> 5. Copy and paste the following code into the console:
> 
> const rrConfig = await SYNOCOMMUNITY.RRManager.SynoApiProvider.callCustomScript("getConfig.cgi");
> localStorage.setItem("rrConfig", JSON.stringify(rrConfig));
> 6. Press Enter.
> 7. Close and reopen RR Manager.

Thx!
Fixed error for me.
DSM 7.2.2-72806 U3
Manager 2.0.83
I think this fix should be intgrated in next release....

**Comment by nhymxu** [comment]
I found that version work well
https://github.com/RROrg/RRManager/releases/tag/3.0-23
